name = "asiseals-email-workers"
main = "src/index.ts"
compatibility_date = "2023-04-13"


send_email = [
  { type = "send_email", name = "SEB", allowed_destination_addresses = [
    "bonjomontes@gmail.com",
  ] },
]
